## Exercícios

Link para Dataset: https://www.kaggle.com/datasets/matheusfreitag/gas-prices-in-brazil

In [6]:
import pandas as pd
df1 = pd.read_csv('gasolina_2000+.csv')
df2 = pd.read_csv('gasolina_2010+.csv')

C:\Users\DNC-PC-203\AppData\Local\Temp\ipykernel_3892\63894417.py:3: DtypeWarning: Columns (12,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('gasolina_2010+.csv')

In [13]:
df1.columns

Index(['Unnamed: 0', 'DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO',
       'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='object')

In [15]:
df2.columns

Index(['Unnamed: 0', 'DATA INICIAL', 'DATA FINAL', 'REGIÃO', 'ESTADO',
       'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'UNIDADE DE MEDIDA',
       'PREÇO MÉDIO REVENDA', 'DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA',
       'PREÇO MÁXIMO REVENDA', 'MARGEM MÉDIA REVENDA',
       'COEF DE VARIAÇÃO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO',
       'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO',
       'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO'],
      dtype='object')

## Neste projeto, trabalharemos com dois arquivos csvs separados, contendo informações sobre o preço da gasolina no Brasil. 

### 1. Carregue os conjuntos de dados "gasolina_2000+.csv" e "gasolina_2010+.csv" em dois DataFrames diferentes e combine-os em um único DataFrame.

In [17]:
df3 = pd.concat([df1,df2])

### 2.Investigue as colunas e entenda o conjunto de dados usando o head() e info()

In [19]:
df3.head(5)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082

### 3. Selecione a terceira entrada da coluna DATA INICIAL e verifique seu tipo.

In [47]:
df3['DATA INICIAL'].loc[2]

2    2004-05-09
2    2011-01-02
Name: DATA INICIAL, dtype: object

### 4. Você deve ter percebido que as colunas DATA INICIAL e DATA FINAL estão formatadas como string. Utilizando o método pd.to_datetime(), converta ambas colunas para Timestamp / Datetime.

In [53]:
df3["DATA INICIAL"] = pd.to_datetime(df3["DATA INICIAL"])
df3["DATA FINAL"] = pd.to_datetime(df3["DATA FINAL"])

### 5. Crie uma nova coluna para representar o ano e o mês(aaaa-mm), utilizando a coluna DATA FINAL como referência.

In [56]:
df3["ANO-MES"] = df3["DATA FINAL"].dt.strftime("%Y-%m")
df3["ANO-MES"]

0        2004-05
1        2004-05
2        2004-05
3        2004-05
4        2004-05
          ...
78180    2021-05
78181    2021-05
78182    2021-05
78183    2021-05
78184    2021-05
Name: ANO-MES, Length: 120823, dtype: object

### 6. Utilizando o value_counts(), liste todos os tipos de produtos contidos na base de dados.

In [59]:
df3.columns
produtos = df3['PRODUTO'].value_counts()

GASOLINA COMUM        23570
GLP                   23561
ETANOL HIDRATADO      23440
ÓLEO DIESEL           21194
GNV                   14469
ÓLEO DIESEL S10        9113
OLEO DIESEL S10        2376
OLEO DIESEL            2351
GASOLINA ADITIVADA      749
Name: PRODUTO, dtype: int64

### 7. Filtre o DataFrame para obter apenas dados da 'GASOLINA COMUM'. Grave em uma nova variável.

In [65]:
df_gasolina = df3.loc[df3["PRODUTO"] == "GASOLINA COMUM"]
df_gasolina

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,ANO-MES
9256,12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,1.990,2.070,0.318,0.003,1.711,0.02,1.651,1.7427,0.012,2004-05
9257,12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,1.850,2.220,0.296,0.031,1.729,0.036,1.6643,1.915,0.021,2004-05
9258,12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,2.000,2.540,0.472,0.028,1.886,0.068,1.75,2.0713,0.036,2004-05
9259,12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,1.970,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,2004-05
9260,12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,2.000,2.159,0.35,0.016,1.74,0.042,1.6789,1.918,0.024,2004-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78083,120721,2021-04-25,2021-05-01,NORTE,RORAIMA,GASOLINA COMUM,12,R$/l,5.364,0.065,5.310,5.530,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
78084,120722,2021-04-25,2021-05-01,SUL,SANTA CATARINA,GASOLINA COMUM,119,R$/l,5.051,0.251,4.640,5.599,-99999.0,0.050,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
78085,120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
78086,120724,2021-04-25,2021-05-01,NORDESTE,SERGIPE,GASOLINA COMUM,34,R$/l,5.586,0.088,5.410,5.699,-99999.0,0.016,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05
78087,120725,2021-04-25,2021-05-01,NORTE,TOCANTINS,GASOLINA COMUM,20,R$/l,5.751,0.160,5.578,6.119,-99999.0,0.028,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,2021-05

### 8. Qual o preço médio de revenda da gasolina em agosto de 2008?

In [75]:
filtro = (df3["DATA FINAL"].dt.month == 8) & (df3["DATA FINAL"].dt.year == 2008)
df_gasolina_agosto_2008 = df3.loc[filtro]

preco_medio = df_gasolina_agosto_2008["PREÇO MÉDIO REVENDA"].mean()

print('O preço Médio da revenda da gasolina em agosto de 2008 é de',round(preco_medio, 2))

O preço Médio da revenda da gasolian em agosto de 2008 é de 9.3

### 9. Qual o preço médio de revenda da gasolina em maio de 2014 em São Paulo?

In [81]:
filtro = (df3["DATA FINAL"].dt.month == 5 ) & (df3["DATA FINAL"].dt.year == 2014) & (df3["ESTADO"] == 'SAO PAULO')
df_gasolina_sp = df3.loc[filtro]

preco_medio_sp = df_gasolina_sp["PREÇO MÉDIO REVENDA"].mean()

preco_medio_sp

8.920766666666667

### 10. Você conseguiria descobrir em qual(quais) estado(s) a gasolina ultrapassou a barreira dos R$ 5,00? E quando isso ocorreu?

In [88]:
preco_maximo_por_estado = df3.groupby("ESTADO").agg({"PREÇO MÉDIO REVENDA": "max"})
preco_maximo_por_estado


estados_acima_de_5_reais = preco_maximo_por_estado.loc[preco_maximo_por_estado["PREÇO MÉDIO REVENDA"] > 5.00]

if len(estados_acima_de_5_reais) == 0:
    print("Não foram encontrados estados com preço máximo acima de R$ 5,00.")
else:
    for estado in estados_acima_de_5_reais.index:
        filtro = (df_gasolina["ESTADO"] == estado) & (df_gasolina["PREÇO MÉDIO REVENDA"] > 5.00)
        datas = df_gasolina.loc[filtro, "DATA FINAL"]
        data_minima = datas.min()
        data_maxima = datas.max()
        print(f"No estado de {estado}, na data de {data_minima} atingiu valor minimo  e na data de  {data_maxima} atingiu valor maximo")

No estado de ACRE, na data de 2018-05-26 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de ALAGOAS, na data de 2021-02-20 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de AMAPA, na data de NaT atingiu valor minimo  e na data de  NaT atingiu valor maximo
No estado de AMAZONAS, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de BAHIA, na data de 2021-02-20 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de CEARA, na data de 2021-02-20 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de DISTRITO FEDERAL, na data de 2021-02-13 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de ESPIRITO SANTO, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de GOIAS, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de MARANHAO, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de MATO GROSSO, na data de 2021-03-06 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de MATO GROSSO DO SUL, na data de 2021-02-20 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de MINAS GERAIS, na data de 2021-02-20 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de PARA, na data de 2021-02-20 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de PARAIBA, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de PARANA, na data de 2021-03-06 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de PERNAMBUCO, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de PIAUI, na data de 2021-02-20 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de RIO DE JANEIRO, na data de 2018-06-09 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de RIO GRANDE DO NORTE, na data de 2021-01-30 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de RIO GRANDE DO SUL, na data de 2021-02-20 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de RONDONIA, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de RORAIMA, na data de 2021-03-06 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de SANTA CATARINA, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de SAO PAULO, na data de 2021-03-06 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de SERGIPE, na data de 2021-02-27 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo
No estado de TOCANTINS, na data de 2018-09-29 00:00:00 atingiu valor minimo  e na data de  2021-05-01 00:00:00 atingiu valor maximo

### 11. Qual a média de preço dos estados da região sul em 2012?

In [110]:
df3['ANO-MES'] = df3['DATA FINAL'].dt.strftime('%Y-%m')
media_preco_sul_2012 = df3.loc[(df3['ESTADO'].isin(['PR', 'SC', 'RS'])) & (df3['ANO-MES'] == '2012-01')]

media = media_preco_sul_2012.groupby(['ESTADO', 'ANO-MES'])['PREÇO MÉDIO REVENDA'].mean()

### 12. Você conseguiria obter uma tabela contendo a variação percentual ano a ano para o estado do Rio de Janeiro?

In [120]:
dfrj = df3[df3['ESTADO'] == 'RIO DE JANEIRO']

dfrj['ANO'] = dfrj['DATA FINAL'].dt.year

dfrj['VARIAÇÃO %'] = dfrj['PREÇO MÉDIO REVENDA'].pct_change()

tabela_variacao_rj = dfrj.groupby('ANO')['VARIAÇÃO %'].mean()

tabela_variacao_rj

C:\Users\DNC-PC-203\AppData\Local\Temp\ipykernel_3892\267202582.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfrj['ANO'] = dfrj['DATA FINAL'].dt.year
C:\Users\DNC-PC-203\AppData\Local\Temp\ipykernel_3892\267202582.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfrj['VARIAÇÃO %'] = dfrj['PREÇO MÉDIO REVENDA'].pct_change()

ANO
2004    0.058196
2005    0.001325
2006    0.000417
2007    0.000354
2008    0.001697
2009    0.000208
2010    0.000729
2011    0.044517
2012    0.000208
2013    1.964693
2014    2.031087
2015    1.951196
2016    1.946559
2017    2.079917
2018    1.947044
2019    1.969859
2020    1.917233
2021    1.658348
Name: VARIAÇÃO %, dtype: float64

### DESAFIO: Crie uma tabela contendo uma serie temporal com a diferença absoluta e percentual entre os valores mais baratos e caros. Apresente também ao lado os estados na qual os maiores e menores preços foram registrados.

In [126]:
# Selecionando apenas a coluna PREÇO MÉDIO REVENDA e agrupando por estado

df_precos_estados = df3.groupby('ESTADO')['PREÇO MÉDIO REVENDA']

# Obtendo os preços máximo e mínimo registrados em cada estado

preco_max = df_precos_estados.max()
preco_min = df_precos_estados.min()

# Calculando a diferença absoluta e percentual entre os preços mais caros e mais baratos registrados em cada estado
dif_abs = preco_max - preco_min
dif_pct = (preco_max / preco_min - 1) * 100


# Obtendo os estados com os maiores e menores preços registrados
estado_maior_preco = dif_abs.idxmax()
estado_menor_preco = dif_abs.idxmin()


# Criando a tabela com a diferença absoluta e percentual entre os preços mais caros e mais baratos registrados em cada estado
tabela_precos = pd.concat([dif_abs, dif_pct], axis=1)
tabela_precos.columns = ['DIFERENÇA ABSOLUTA', 'DIFERENÇA PERCENTUAL']
tabela_precos['MAIOR PREÇO'] = preco_max
tabela_precos['MENOR PREÇO'] = preco_min
tabela_precos['ESTADO MAIOR PREÇO'] = estado_maior_preco
tabela_precos['ESTADO MENOR PREÇO'] = estado_menor_preco


print(tabela_precos)

                     DIFERENÇA ABSOLUTA  DIFERENÇA PERCENTUAL  MAIOR PREÇO  \
ESTADO
ACRE                            105.787           6175.539988      107.500
ALAGOAS                          82.032           7637.988827       83.106
AMAPA                           102.163           6792.752660      103.667
AMAZONAS                         91.384           6532.094353       92.783
BAHIA                            79.139           7334.476367       80.218
CEARA                            90.543           7660.152284       91.725
DISTRITO FEDERAL                 79.707           6554.851974       80.923
ESPIRITO SANTO                   83.382           7346.431718       84.517
GOIAS                            88.082           7580.206540       89.244
MARANHAO                         86.573           6711.085271       87.863
MATO GROSSO                     103.990           8637.043189      105.194
MATO GROSSO DO SUL               85.031           7751.230629       86.128
MINAS GERAIS                     85.981           7746.036036       87.091
PARA                             91.785           6218.495935       93.261
PARAIBA                          84.954           7393.733681       86.103
PARANA                           87.409           9480.368764       88.331
PERNAMBUCO                       78.888           7896.696697       79.887
PIAUI                            86.776           6480.657207       88.115
RIO DE JANEIRO                   75.811           7317.664093       76.847
RIO GRANDE DO NORTE              90.198           9251.076923       91.173
RIO GRANDE DO SUL                81.202           6952.226027       82.370
RONDONIA                         99.206           8138.310090      100.425
RORAIMA                         101.575           7813.461538      102.875
SANTA CATARINA                   89.992           7518.128655       91.189
SAO PAULO                        84.574          11040.992167       85.340
SERGIPE                          82.353           7130.129870       83.508
TOCANTINS                        93.445           7621.941272       94.671

                     MENOR PREÇO ESTADO MAIOR PREÇO ESTADO MENOR PREÇO
ESTADO
ACRE                       1.713               ACRE     RIO DE JANEIRO
ALAGOAS                    1.074               ACRE     RIO DE JANEIRO
AMAPA                      1.504               ACRE     RIO DE JANEIRO
AMAZONAS                   1.399               ACRE     RIO DE JANEIRO
BAHIA                      1.079               ACRE     RIO DE JANEIRO
CEARA                      1.182               ACRE     RIO DE JANEIRO
DISTRITO FEDERAL           1.216               ACRE     RIO DE JANEIRO
ESPIRITO SANTO             1.135               ACRE     RIO DE JANEIRO
GOIAS                      1.162               ACRE     RIO DE JANEIRO
MARANHAO                   1.290               ACRE     RIO DE JANEIRO
MATO GROSSO                1.204               ACRE     RIO DE JANEIRO
MATO GROSSO DO SUL         1.097               ACRE     RIO DE JANEIRO
MINAS GERAIS               1.110               ACRE     RIO DE JANEIRO
PARA                       1.476               ACRE     RIO DE JANEIRO
PARAIBA                    1.149               ACRE     RIO DE JANEIRO
PARANA                     0.922               ACRE     RIO DE JANEIRO
PERNAMBUCO                 0.999               ACRE     RIO DE JANEIRO
PIAUI                      1.339               ACRE     RIO DE JANEIRO
RIO DE JANEIRO             1.036               ACRE     RIO DE JANEIRO
RIO GRANDE DO NORTE        0.975               ACRE     RIO DE JANEIRO
RIO GRANDE DO SUL          1.168               ACRE     RIO DE JANEIRO
RONDONIA                   1.219               ACRE     RIO DE JANEIRO
RORAIMA                    1.300               ACRE     RIO DE JANEIRO
SANTA CATARINA             1.197               ACRE     RIO DE JANEIRO
SAO PAULO                  0.766               ACRE     RIO DE JANEIRO
SERGIPE                    1.155               ACRE     RIO DE JANEIRO
TOCANTINS                  1.226               ACRE     RIO DE JANEIRO